image: gengjiawen/android-ndk:qa-2020-07-31

stages:
  - build

buildNative:
  stage: build
  script:
    - cd mockup/platform/android
    - ./gradlew checkstyle
    - cd ../../../
    - sh scan_build.sh
    - cd mockup/platform/android
    - ./gradlew --no-daemon clean assembleRelease
  artifacts:
    when: on_failure
    paths:
      - mockup/platform/android/app/build/reports/checkstyle/checkstyle.html
  tags:
    - docker
